# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubernetesBinariesManagers < Formula
  desc "Kubernetes-Binaries-Managers is a project to help manage kubernetes related binaries."
  homepage "https://github.com/little-angry-clouds/kubernetes-binaries-managers/"
  version "1.0.0"
  license "GPL3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_darwin_arm64.tar.gz"
      sha256 "e56712abaf8c6d101079c513b9c1226a13933d78c562895552a52c88a98c3030"

      def install
        bin.install "kubernetes-binaries-managers"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_darwin_amd64.tar.gz"
      sha256 "c35c883879975256aaab127465d18a1741e36f22ffe0b334b891a4ca702b9cd5"

      def install
        bin.install "kubernetes-binaries-managers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_linux_armv6.tar.gz"
      sha256 "01bf66c0e6f7f257edc40695e8377d4e5e4b8b1b0c20b3d774a78579f343bf95"

      def install
        bin.install "kubernetes-binaries-managers"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_linux_amd64.tar.gz"
      sha256 "7db28416a31734db310d210377a7cbb4af307dc3d744eb70f7f1423f842e4cba"

      def install
        bin.install "kubernetes-binaries-managers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_linux_arm64.tar.gz"
      sha256 "1a15a9d67eadf2a906684f572076802f25e49886151d7c79b4525460d52837d1"

      def install
        bin.install "kubernetes-binaries-managers"
      end
    end
  end
end
