# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocenv < Formula
  desc "Oc version manager inspired by tfenv"
  homepage "https://github.com/little-angry-clouds/kubernetes-binaries-managers/"
  license "GPL3"

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_linux_arm.tar.gz"
      sha256 "26fc77f4cf7d990b67c3b3cd3589a19dce61df06aa49f44ccb3266ff881fdac4"

      def install
        bin.install "oc-linux-arm/ocenv"
        bin.install "oc-linux-arm/oc-wrapper" => "oc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_linux_arm64.tar.gz"
      sha256 "24b7bc2901e9aa9d6f215ba17dad62ccfd17f909367aa151b5dffdac6cf341e3"

      def install
        bin.install "oc-linux-arm64/ocenv"
        bin.install "oc-linux-arm64/oc-wrapper" => "oc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_linux_amd64.tar.gz"
      sha256 "47bb227c2cf1ee7fae8ebb7f4d9cdcd797fdde1ef0b82a214a945e5e685898f0"

      def install
        bin.install "oc-linux-amd64/ocenv"
        bin.install "oc-linux-amd64/oc-wrapper" => "oc"
      end
    end
  end

  on_macos do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_darwin_arm64.tar.gz"
      sha256 "ddaf850a3cad2a33ee1e9bfc42fd11f2c5ff98db3199b610efc0c785f6c0f6e7"

      def install
        bin.install "oc-darwin-arm64/ocenv"
        bin.install "oc-darwin-arm64/oc-wrapper" => "oc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/kubernetes-binaries-managers/releases/download/v1.0.0/kubernetes-binaries-managers_1.0.0_darwin_amd64.tar.gz"
      sha256 "6dacb37b5b5225bf4dacc0ba34750adf8cb7ee557e0e92acfdb9554f4ecc97bf"

      def install
        bin.install "oc-darwin-amd64/ocenv"
        bin.install "oc-darwin-amd64/oc-wrapper" => "oc"
      end
    end
  end

end
