# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Particle < Formula
  desc "Particle is a project designed to aid in the development and testing of Helm charts and other kubernetes manifests."
  homepage "https://github.com/little-angry-clouds/particle/"
  version "0.0.5"
  license "GPL3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/particle/releases/download/v0.0.5/particle_0.0.5_darwin_amd64.tar.gz"
      sha256 "6c9a88834869e56f189aebb0710b6b3e1b0d0517bfcdcdedb90fe274ac05a607"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/particle/releases/download/v0.0.5/particle_0.0.5_linux_amd64.tar.gz"
      sha256 "5efde14d0d088f02d08902f06a49610e078131cfa435dc7da57b2249779833cd"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/particle/releases/download/v0.0.5/particle_0.0.5_linux_armv6.tar.gz"
      sha256 "3d0022ff8fba69846cffbd21f6b92546e512a3ac1060593d8612f2c329330a28"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/particle/releases/download/v0.0.5/particle_0.0.5_linux_arm64.tar.gz"
      sha256 "6590093659bf49cb7de94e99ed3c468f9ccebdeb192e97bf5d9079073e91bfbd"
    end
  end

  depends_on "go"
  depends_on "helm" => :optional
  depends_on "kind" => :optional

  def install
    bin.install "particle"
  end
end
