# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Particle < Formula
  desc "Particle is a project designed to aid in the development and testing of Helm charts and other kubernetes manifests."
  homepage "https://github.com/little-angry-clouds/particle/"
  version "0.0.1"
  license "GPL3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/homebrew-my-brewsv0.0.1/particle_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "8040a6cf92823d75e4af728b411e35271cdcd34b8dfd7326fd84b550b3efac5a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/little-angry-clouds/homebrew-my-brewsv0.0.1/particle_0.0.1_Darwin_arm64.tar.gz"
      sha256 "06dac9de21060098ecb6ba3ca62d42f2000a04d492f0a8e72b5a72f87ae33330"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/little-angry-clouds/homebrew-my-brewsv0.0.1/particle_0.0.1_Linux_x86_64.tar.gz"
      sha256 "f3bd71f22e50199fb0726395adaf5fcc45209f3051a8b428d4a56d0700246488"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/little-angry-clouds/homebrew-my-brewsv0.0.1/particle_0.0.1_Linux_arm64.tar.gz"
      sha256 "601f0c585dc50f4a956d7c2a1724ba6e34448e8e782d0e9273b152d715b7f716"
    end
  end

  depends_on "go"
  depends_on "helm" => :optional
  depends_on "kind" => :optional

  def install
    ENV.prepend "CGO_ENABLED", "0"
    system "go", "build", "-a", "-o", "particle.bin", "main.go"
    bin.install "particle.bin" => "#{bin}/particle"
  end
end
